server:
  port: 9000

auth:
  issuer-uri: http://localhost:9000
  access-token-ttl: PT30M
  refresh-token-ttl: P1D
  clients:
    dashboard:
      client-id: bifrost-dashboard
      client-secret: ${BIFROST_DASHBOARD_SECRET:dashboard-secret}
      redirect-uris:
        - http://localhost:3000/api/auth/callback/bifrost
      allowed-scopes:
        - openid
        - profile
        - email
  cors-allowed-origins:
    - http://localhost:3000
    - http://localhost:3001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: bifrost_user
    password: bifrost_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      suffix: .html
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.scottylabs.auth: DEBUG
