import z from "zod";

export const applicationSchema = z.object({
  name: z.string().nonempty(),
  email: z.string().email(),
  phone: z.string().regex(/^\d{10}$/),
  school: z.string().min(1),
  grade: z.enum(["Freshman", "Sophomore", "Junior", "Senior"]),
  age: z.coerce.number().int().positive(),
  gender: z.enum(["male", "female", "other"]),
  ethnicity: z.enum(["white", "black", "asian", "hispanic", "other"]),
  city: z.string().min(1),
  major: z.string().min(1),
  relevantCoursework: z.array(z.string().min(1)),
  programmingLanguages: z.array(z.string().min(1)),
  previousProgrammingExperience: z.boolean(),
  essayQuestion1: z.string(),
  github: z.string().url(),
  linkedin: z.string().url(),
  resume: z.string().url(),
  designPortfolio: z.string().url(),
  dietaryRestrictions: z.string(),
  tshirtSize: z.enum(["XS", "S", "M", "L", "XL", "XXL"]),
  accessibilityNeeds: z.string(),
  travelReimbursementAcknowledgement: z.boolean(),
  travelReimbursementDetails: z.string(),
  codeOfConductAcknowledgement: z.boolean(),
  privacyPolicyAcknowledgement: z.boolean(),
  termsAndConditionsAcknowledgement: z.boolean(),
  photoReleaseAcknowledgement: z.boolean(),
});
