version: "3.8"

name: bifrost

services:
  postgres:
    image: postgres:16
    container_name: bifrost-postgres
    environment:
      POSTGRES_USER: bifrost_user
      POSTGRES_PASSWORD: bifrost_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  resource-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: resource-app
    environment:
      AUTH_ALLOWED_ORIGINS: "http://localhost:5173/"
      AUTH_ISSUER_URI: "https://eloquent-bardeen-hsgstmum1n.projects.oryapis.com"
      AUTH_JWKS_URI: "https://eloquent-bardeen-hsgstmum1n.projects.oryapis.com/.well-known/jwks.json"
      ORY_WEBHOOK_AUTH_KEY_NAME: "authentication-key"
      ORY_WEBHOOK_AUTH_KEY_VALUE: "fae574a753f4b0cfdb59e25699f80cbb1fdd6a2d709062966ca9f7e21e80fad5"
      SPRING_PROFILES_ACTIVE: "dev"
      GRADLE_USER_HOME: "/app/.gradle"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./settings.gradle.kts:/app/settings.gradle.kts
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./gradle:/app/gradle
      - ./resource:/app/resource
      - gradle-cache:/app/.gradle

volumes:
  postgres_data:
  pgadmin_data:
  gradle-cache:
