create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255), primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255) not null, primary key (user_id, role));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) not null check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255) not null unique, primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255) not null, primary key (user_id, role));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) not null check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255) not null unique, primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
create table applications (id uuid not null, user_id uuid not null unique, design_portfolio varchar(255), essay_question1 varchar(255) not null, essay_question2 varchar(255) not null, github varchar(255), resume_file_path varchar(255), primary key (id));
create table checkins (active boolean not null, enable_self_checkin boolean not null, points integer not null, end_time bigint not null, start_time bigint not null, event_id uuid not null, id uuid not null, access_level varchar(255) check (access_level in ('PARTICIPANT','MENTOR','SPONSOR','JUDGE','ORGANIZER','ADMIN')), description varchar(255) not null, name varchar(255) not null, primary key (id));
create table events (end_date timestamp(6) not null, start_date timestamp(6) not null, id uuid not null, logo varchar(255), name varchar(255) not null, website varchar(255), primary key (id));
create table prizes (id uuid not null, description varchar(255) not null, name varchar(255) not null, provider varchar(255) not null, value varchar(255) not null, primary key (id));
create table projects (id uuid not null, prize_id uuid, team_id uuid, track_id uuid, description varchar(255) not null, location varchar(255), name varchar(255) not null, slides varchar(255), url varchar(255), video varchar(255), primary key (id));
create table teams (open boolean not null, id uuid not null, leader_id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tracks (id uuid not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table user_checkins (timestamp timestamp(6) not null, checkin_id uuid not null, id uuid not null, user_id uuid not null, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255) not null, primary key (user_id, role));
create table users (id uuid not null, team_id uuid, college varchar(255) not null, email varchar(255) not null unique, name varchar(255) not null, status varchar(255) not null check (status in ('UNVERIFIED','VERIFIED','COMPLETED_PROFILE','ADMITTED','REJECTED','CONFIRMED','DECLINED','WAITLISTED')), username varchar(255) not null unique, primary key (id));
alter table if exists applications add constraint FKfsfqljedcla632u568jl5qf3w foreign key (user_id) references users;
alter table if exists checkins add constraint FK97wab30ijvjle2fghs1vr6pbj foreign key (event_id) references events;
alter table if exists projects add constraint FKcx3mkd9g2xjtjdrrto5ogorp3 foreign key (prize_id) references prizes;
alter table if exists projects add constraint FKmqih0928bq6r3gbuh47giq8w foreign key (team_id) references teams;
alter table if exists projects add constraint FK533ndosai0wx9ml2awcdqvurq foreign key (track_id) references tracks;
alter table if exists teams add constraint FK1unglgeiypxqm05k3sxh7web4 foreign key (leader_id) references users;
alter table if exists user_checkins add constraint FK6gl044lv15mldhv4njdh7c2q4 foreign key (checkin_id) references checkins;
alter table if exists user_checkins add constraint FK11b2pmttn0epwarkjxw349poq foreign key (user_id) references users;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKfjws1rdruab2bqg7qipoqf65r foreign key (team_id) references teams;
