spring:
  datasource:
    url: jdbc:postgresql://bifrost-postgres:5432/resource
    username: bifrost_user
    password: bifrost_password

  jpa:
    hibernate:
      ddl-auto: create-drop

  liquibase:
    enabled: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true

logging:
  level:
    root: INFO
    com.bifrost: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG
